### PR TITLE
Hotfixes for nodes

### PR DESCRIPTION
**Pull request by k----n**

### CODE REVIEW

**Comment by emmettu** [comment]
This will be the ONE-HUNDREDTH-CLOSED-PR

**Review by iameric1986 — DISMISSED** [review]

**Review by iameric1986 — COMMENTED** [review]
Line 172 in node/models.py

Please look at slack to see my question

**Comment by iameric1986** [comment]
This issue was resolved without these changes. Still merge?

**Comment by k----n** [comment]
It's a good safety net just in case another node connects to another node

**Pull request merged**
